const vocabulary = [
    { category: "Shopping & Stores", german: "das Geschäft", plural: "-e", english: "shop, business" },
    { category: "Shopping & Stores", german: "der Laden", plural: "Läden", english: "shop, store" },
    { category: "Shopping & Stores", german: "das Kaufhaus", plural: "Kaufhäuser", english: "department store" },
    { category: "Shopping & Stores", german: "das Warenhaus", plural: "Warenhäuser", english: "department store" },
    { category: "Shopping & Stores", german: "das Einkaufszentrum", plural: "-en", english: "shopping center/mall" },
    { category: "Shopping & Stores", german: "die Verkaufstheke", plural: "-n", english: "sales counter" },
    { category: "Shopping & Stores", german: "der Ladentisch", plural: "-e", english: "shop counter" },
    { category: "Shopping & Stores", german: "der Einkaufswagen", plural: "-", english: "shopping cart" },
    { category: "Shopping & Stores", german: "einkaufen, Einkäufe machen", plural: "", english: "to shop, to do shopping" },
    { category: "Shopping & Stores", german: "kaufen", plural: "", english: "to buy" },
    { category: "Shopping & Stores", german: "der Nachlass", plural: "Nachlässe", english: "discount" },
    { category: "Shopping & Stores", german: "der Rabatt", plural: "-e", english: "discount" },
    { category: "Shopping & Stores", german: "das Sonderangebot", plural: "-e", english: "special offer" },
    { category: "Shopping & Stores", german: "der Ausverkauf", plural: "-e", english: "clearance sale" },
    { category: "Shopping & Stores", german: "der Sonderpreis", plural: "-e", english: "special price" },
    { category: "Shopping & Stores", german: "etwas (sehr) günstig kaufen", plural: "", english: "to buy something (very) cheaply" },

    { category: "People", german: "der Kunde / die Kundin", plural: "-n / -nen", english: "customer" },
    { category: "People", german: "der Verkäufer / die Verkäuferin", plural: "- / -nen", english: "salesperson" },
    { category: "People", german: "der Kassierer / die Kassiererin", plural: "- / -nen", english: "cashier" },

    { category: "Paying & Money", german: "zahlen", plural: "", english: "to pay" },
    { category: "Paying & Money", german: "bezahlen/zahlen", plural: "", english: "to pay (with/by)" },
    { category: "Paying & Money", german: "das Bargeld", plural: "", english: "cash" },
    { category: "Paying & Money", german: "bar zahlen", plural: "", english: "to pay in cash" },
    { category: "Paying & Money", german: "der (Geld)schein / die Banknote", plural: "-e / -n", english: "banknote" },
    { category: "Paying & Money", german: "die Münze / das Geldstück", plural: "-n / -e", english: "coin" },
    { category: "Paying & Money", german: "die Kreditkarte", plural: "-n", english: "credit card" },
    { category: "Paying & Money", german: "der Scheck", plural: "", english: "check" },
    { category: "Paying & Money", german: "einen Scheck ausstellen", plural: "", english: "to write a check" },
    { category: "Paying & Money", german: "die Kasse", plural: "-n", english: "cash register, checkout" },
    { category: "Paying & Money", german: "die Registrierkasse", plural: "-n", english: "cash register" },
    { category: "Paying & Money", german: "die Ladenkasse", plural: "-n", english: "shop cash register" },
    { category: "Paying & Money", german: "die Quittung / der Bon", plural: "-en / -s", english: "receipt" },

    { category: "Clothes & Theft", german: "die Kabine / die Umkleidekabine", plural: "-n", english: "fitting room, changing room" },
    { category: "Clothes & Theft", german: "anprobieren", plural: "", english: "to try on" },
    { category: "Clothes & Theft", german: "die Handtasche", plural: "-n", english: "handbag" },
    { category: "Clothes & Theft", german: "die Brieftasche", plural: "-n", english: "wallet, purse" },
    { category: "Clothes & Theft", german: "das Portemonee", plural: "-s", english: "purse (for coins), wallet" },
    { category: "Clothes & Theft", german: "Ladendiebstahl", plural: "", english: "shoplifting" },

    { category: "Shops", german: "die Apotheke", plural: "-n", english: "pharmacy" },
    { category: "Shops", german: "die Bäckerei", plural: "-en", english: "bakery" },
    { category: "Shops", german: "das Blumengeschäft", plural: "-e", english: "flower shop" },
    { category: "Shops", german: "die Buchhandlung", plural: "-en", english: "bookshop" },
    { category: "Shops", german: "der Friseursalon", plural: "-s", english: "hairdresser's salon" },
    { category: "Shops", german: "das Fischgeschäft / die Fischhandlung", plural: "-e / -en", english: "fish shop" },
    { category: "Shops", german: "das Fotogeschäft", plural: "-e", english: "photography shop" },
    { category: "Shops", german: "die Drogerie", plural: "-n", english: "drugstore" },
    { category: "Shops", german: "der Gemüseladen / die Gemüsehandlung", plural: "Gemüseläden / -en", english: "vegetable shop" },
    { category: "Shops", german: "der Juwelierladen / das Juweliergeschäft", plural: "Juwelierläden / -e", english: "jeweler's shop" },
    { category: "Shops", german: "die Eisen(waren)handlung", plural: "-en", english: "hardware store" },
    { category: "Shops", german: "die Reinigung", plural: "-en", english: "dry cleaner's" },
    { category: "Shops", german: "die Fleischerei / die Metzgerei", plural: "-en", english: "butcher's shop" },
    { category: "Shops", german: "das Spielwarengeschäft", plural: "-e", english: "toy shop" },
    { category: "Shops", german: "das Lebensmittelgeschäft", plural: "-e", english: "grocery store" },
    { category: "Shops", german: "das Modegeschäft", plural: "-e", english: "fashion shop" },
    { category: "Shops", german: "das Musikgeschäft", plural: "-e", english: "music shop" },
    { category: "Shops", german: "das Möbelgeschäft", plural: "-e", english: "furniture store" },
    { category: "Shops", german: "der Optiker", plural: "-", english: "optician" },
    { category: "Shops", german: "das Schreibwarengeschäft", plural: "-e", english: "stationery shop" },
    { category: "Shops", german: "das Schallplattengeschäft", plural: "-e", english: "record shop" },
    { category: "Shops", german: "der Schuhladen / das Schuhgeschäft", plural: "Schuhläden / -e", english: "shoe shop" },
    { category: "Shops", german: "der Selbstbedienungsladen", plural: "Selbstbedienungsläden", english: "self-service shop" },
    { category: "Shops", german: "die Schnellwäscherei", plural: "-en", english: "quick laundry/launderette" },
    { category: "Shops", german: "der Andenkenladen", plural: "Andenkenläden", english: "souvenir shop" },
    { category: "Shops", german: "das Sportgeschäft", plural: "-e", english: "sports shop" },
    { category: "Shops", german: "der Supermarkt", plural: "Supermärkte", english: "supermarket" },
    { category: "Shops", german: "der Zeitungskiosk / der Zeitungsstand", plural: "-e / Zeitungsstände", english: "newsstand/kiosk" },
    { category: "Shops", german: "der Tabakladen", plural: "Tabakläden", english: "tobacconist's shop" },
    { category: "Shops", german: "die Wein- und Spirituosenhandlung", plural: "-en", english: "wine and liquor store" },

    { category: "Phrases", german: "Was darf es sein?", plural: "", english: "What can I get for you?" },
    { category: "Phrases", german: "Guten Tag. Sie wünschen?", plural: "", english: "Good day. What would you like?" },
    { category: "Phrases", german: "Ja, bitte? / Bitte schön?", plural: "", english: "Yes, please? / May I help you?" },
    { category: "Phrases", german: "Kann ich Ihnen helfen?", plural: "", english: "Can I help you?" },
    { category: "Phrases", german: "Welche Größe haben Sie?", plural: "", english: "What size are you?" },
    { category: "Phrases", german: "Das macht ... Mark/Euro, bitte.", plural: "", english: "That comes to ... Marks/Euros, please." },
    { category: "Phrases", german: "Ich schaue erst einmal. / Ich sehe mich nur um.", plural: "", english: "I'm just looking first." },
    { category: "Phrases", german: "Können Sie mir helfen?", plural: "", english: "Can you help me?" },
    { category: "Phrases", german: "Ich suche...", plural: "", english: "I am looking for..." },
    { category: "Phrases", german: "Haben Sie...?", plural: "", english: "Do you have...?" },
    { category: "Phrases", german: "Ich hätte gern/möchte...", plural: "", english: "I would like/want..." },
    { category: "Phrases", german: "Kann ich ihn/sie/es mal anprobieren?", plural: "", english: "Can I try it (masc/fem/neut) on?" },
    { category: "Phrases", german: "Wo ist die (Umkleide)kabine?", plural: "", english: "Where is the (changing) room?" },
    { category: "Phrases", german: "Was/Wie viel kostet/kosten...?", plural: "", english: "What/How much does it cost/do they cost...?" },
    { category: "Phrases", german: "Das ist zu teuer.", plural: "", english: "That is too expensive." },
    { category: "Phrases", german: "Ich nehme ihn/sie/es.", plural: "", english: "I will take it (masc/fem/neut)." },
    { category: "Phrases", german: "Ich hätte gern eine Tragetüte.", plural: "", english: "I would like a shopping bag." },
    { category: "Phrases", german: "Es tut mir Leid, aber das haben wir nicht.", plural: "", english: "I am sorry, but we don't have that." },
    { category: "Phrases", german: "Es ist leider ausverkauft.", plural: "", english: "Unfortunately, it is sold out." }
];
